// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZya5TP0Tt9sXQ_tZWittqIgjIxJRrWIY',
    appId: '1:384243493921:web:03e4b54dba26bb7e5a4760',
    messagingSenderId: '384243493921',
    projectId: 'qnquizz',
    authDomain: 'qnquizz.firebaseapp.com',
    storageBucket: 'qnquizz.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDK-hikdQiujHp3RnzZl8Uzg1NwNfJjw7Y',
    appId: '1:384243493921:android:dff354ace17b914f5a4760',
    messagingSenderId: '384243493921',
    projectId: 'qnquizz',
    storageBucket: 'qnquizz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYZ1CPxiSk9zcRDAxWsFusObVEa2hEGQE',
    appId: '1:384243493921:ios:6e1a0eadfdd7e7f35a4760',
    messagingSenderId: '384243493921',
    projectId: 'qnquizz',
    storageBucket: 'qnquizz.appspot.com',
    iosBundleId: 'com.example.quizapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYZ1CPxiSk9zcRDAxWsFusObVEa2hEGQE',
    appId: '1:384243493921:ios:6e1a0eadfdd7e7f35a4760',
    messagingSenderId: '384243493921',
    projectId: 'qnquizz',
    storageBucket: 'qnquizz.appspot.com',
    iosBundleId: 'com.example.quizapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZya5TP0Tt9sXQ_tZWittqIgjIxJRrWIY',
    appId: '1:384243493921:web:fbfe086a5f032c815a4760',
    messagingSenderId: '384243493921',
    projectId: 'qnquizz',
    authDomain: 'qnquizz.firebaseapp.com',
    storageBucket: 'qnquizz.appspot.com',
  );

}